ERROR   2021-04-08 13:33:22,895 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:34:06,142 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:35:40,391 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:36:30,478 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:37:26,535 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:38:07,623 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:38:40,500 root.data_access.fet Bad jointure 'Duck' for class Users: No field 'Duck' for 'Users'!'
ERROR   2021-04-08 13:39:57,583 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:41:13,183 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
ERROR   2021-04-08 13:41:24,599 root.data_access.fet Bad jointure 'LaBombe' for class Users: No field 'LaBombe' for 'Users'!'
